# -*- coding: utf-8 -*-
# Developer: Esau Ngoma <ngomaesau004@gmail.com>
{
    'name': 'Forecourt Operations',
    'version': '18.0.1.3.0',
    'summary': 'Fuel, LPG and Lubricant Sales, Inventory and Forecourt Management',
    'category': 'Industries',
    'author': 'Kopparapu Dev',
    # Related forecourt suite modules (install separately, not true dependencies):
    # forecourt_credit_import, forecourt_dashboard, forecourt_whatsapp_import, forecourt_shift_capture
    'depends': ['account', 'stock', 'product', 'point_of_sale', 'mail'],
    'data': [
        'security/forecourt_groups.xml',
        'security/ir.model.access.csv',
        'security/forecourt_multi_company_rules.xml',
        'views/forecourt_price_history_views.xml',
        'views/forecourt_product_overview_views.xml',
        'data/forecourt_data.xml',
        'views/forecourt_product_views.xml',
        'views/forecourt_warehouse_views.xml',
        'views/forecourt_tank_views.xml',
        'views/forecourt_pump_views.xml',
        'views/forecourt_shift_views.xml',
        'views/forecourt_sale_views.xml',
        'views/forecourt_delivery_views.xml',
        'views/forecourt_dip_views.xml',
        'views/forecourt_meter_views.xml',
        'views/forecourt_cash_recon_views.xml',
        'views/forecourt_target_views.xml',
        'views/forecourt_menu.xml',
        'views/forecourt_shift_report_wizard_view.xml',
        'views/forecourt_sales_report_wizard_view.xml',
        'views/forecourt_reconciliation_wizard_view.xml',
        'views/forecourt_daily_report_wizard_view.xml',
        'views/pos_fuel_report_wizard_view.xml',
        'views/forecourt_reports_menu.xml',
        'report/forecourt_shift_report_template.xml',
        'report/forecourt_sales_report_template.xml',
        'report/forecourt_reconciliation_report_template.xml',
        'report/forecourt_daily_report_template.xml',
        'report/pos_fuel_report_template.xml',
        'report/forecourt_report_actions.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
    'license': 'LGPL-3',
    'post_init_hook': 'post_init_hook',
}
